//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webnc_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Baihat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Baihat()
        {
            this.Chitietlists = new HashSet<Chitietlist>();
        }
    
        public int IDSong { get; set; }
        public string Tenbai { get; set; }
        public string Casi { get; set; }
        public string Thoiluong { get; set; }
        public string Theloai { get; set; }
        public string Linkbaihat { get; set; }
        public string Img { get; set; }
        public Nullable<int> LuotThich { get; set; }
        public string IDCasi { get; set; }
        public string Trangthaibaihat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitietlist> Chitietlists { get; set; }
        public virtual User User { get; set; }
    }
}
