//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webnc_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chitietlist
    {
        public string IDlist { get; set; }
        public int IDsong { get; set; }
        public int ID { get; set; }
    
        public virtual Baihat Baihat { get; set; }
        public virtual Danhsachphat Danhsachphat { get; set; }
    }
}
