//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webnc_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Danhsachphat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Danhsachphat()
        {
            this.Chitietlists = new HashSet<Chitietlist>();
        }
    
        public string IDlist { get; set; }
        public string Email { get; set; }
        public string Tendanhsach { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitietlist> Chitietlists { get; set; }
        public virtual User User { get; set; }
    }
}
